### ISSUE TITLE
UI:TEST ISSUE

### ISSUE THREAD

**Issue by MrPuzatyi** [gh-xcast/xcast#1]
**Опишите проблему**
Test issue

**Возпроизвести**
1. Go to service site
1. Press button
3. Choose option
4. Press Select

**Ожидаемое поведение**
Windows appears

**Скриншоты**

**Рабочий стол:**

**Вывод консоли браузера**

Нажмите <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>I</kbd>, перейдите к вкладке **Консоль** и скопируйте содержимое.

**Comment by MrPuzatyi** [comment]
test comment

**Comment by dcykhub** [comment]
Testing done. Closed.
